' ... existing code ...

Private Sub btnCrearArchivo_Click()
    ' ... existing code ...
    btnCrearArchivo.BackColor = &H00FFFF00 ' Yellow color
    ' ... existing code ...
End Sub

' ... existing code ...
